"""empty message

Revision ID: 968e1f25dfdc
Revises: b319a08cea30
Create Date: 2021-04-30 01:46:40.014001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968e1f25dfdc'
down_revision = 'b319a08cea30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sitios', sa.Column('costo_max', sa.Integer(), nullable=True))
    op.add_column('sitios', sa.Column('costo_min', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sitios', 'costo_min')
    op.drop_column('sitios', 'costo_max')
    # ### end Alembic commands ###
