"""empty message

Revision ID: be4049e10f0f
Revises: 87309eb13544
Create Date: 2021-04-30 04:06:53.857120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4049e10f0f'
down_revision = '87309eb13544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sitios', sa.Column('gmaps', sa.String(length=120), nullable=True))
    op.add_column('sitios', sa.Column('lat', sa.String(length=120), nullable=True))
    op.add_column('sitios', sa.Column('lon', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sitios', 'lon')
    op.drop_column('sitios', 'lat')
    op.drop_column('sitios', 'gmaps')
    # ### end Alembic commands ###
