"""empty message

Revision ID: dff1b0ab33d3
Revises: 51cbb930a3c8
Create Date: 2021-04-23 02:20:34.963540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff1b0ab33d3'
down_revision = '51cbb930a3c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=120), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('sitio_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sitio_id'], ['sitios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sitios_usuarios',
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('sitio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sitio_id'], ['sitios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sitios_usuarios')
    op.drop_table('calificaciones')
    # ### end Alembic commands ###
